[package]
name = "assembler"
version = "0.1.0"
authors = [
	"Lieuwe Rooijakkers <lieuwerooijakkers@gmail.com>",
	"Tom Smeding <tomsmeding@gmail.com>"
]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.2.0"
